# Generated by Django 4.2 on 2024-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_post_notification_comment_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
