# Generated by Django 4.2 on 2024-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_comment_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
